import React, { ReactElement } from "react"
import { ToastContainer } from "react-toastify"
import type { Metadata } from "next"
import "@styles/global.scss"
import "@styles/font.scss"
import "@styles/toast.scss"
import Container from "@components/Container"
import SuspenseWrapper from "@components/SuspenseWrapper"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>): ReactElement {
    return (
        <html lang="en">
            <head>
                <title>{"Toadx2 | 두껍아두껍아"}</title>
                <link rel="icon" href="/pepe.png" />
            </head>
            <body>
                <SuspenseWrapper>
                    <Container>
                        {children}
                        <ToastContainer
                            position="bottom-right"
                            autoClose={1800}
                            hideProgressBar={false}
                            newestOnTop={false}
                            closeOnClick
                            rtl={false}
                            pauseOnFocusLoss
                            draggable
                            pauseOnHover
                            theme="light"
                        />
                    </Container>
                </SuspenseWrapper>
            </body>
        </html>
    )
}
